name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Nx build (libs only)
        run: |
          npx nx run-many -t build -p=runtime-i18n,runtime-i18n-angular --configuration=production

      - name: Nx test (libs only)
        run: |
          npx nx run-many -t test -p=runtime-i18n,runtime-i18n-angular
