name: Publish to npm (with token)
on:
  push:
    tags:
      - 'runtime-i18n@*'
      - 'runtime-i18n-angular@*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build all libs
        run: |
          npx nx run-many -t build -p=runtime-i18n,runtime-i18n-angular --configuration=production

      - name: Publish @ngx-runtime-i18n/core
        if: startsWith(github.ref_name, 'runtime-i18n@')
        working-directory: dist/libs/runtime-i18n
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Publish @ngx-runtime-i18n/angular
        if: startsWith(github.ref_name, 'runtime-i18n-angular@')
        working-directory: dist/libs/runtime-i18n-angular
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
